tasks:
  tests:
    - tox -e py34
    - tox -e flake8
    - tox -e isort
    - coverage xml
  after_success:
    - git config --global user.name "semantic-release"
    - git config --global user.email "semantic-release@frigg"
    - pip3 install python-semantic-release
    - semantic-release publish

coverage:
  path: coverage.xml
  parser: python
